name: "SLATE Novel Writing Tools"
description: "Specialized tools for fiction writers and TUI development"
version: "1.0.0"
base_path: "."
author: "SLATE TUI Ecosystem"
website: "https://github.com/slate-tui"

# Domain-specific configuration
settings:
  default_genre: "fantasy"
  word_count_target: 80000
  chapter_target: 25